default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: restaurant_development
  username: restaurant
  password: password
  host: localhost


test:
  <<: *default
  database: restaurant_test

production:
  <<: *default
  database: restaurant_production
  username: restaurant
  password: <%= ENV['RESTAURANT_DATABASE_PASSWORD'] %>
